### ISSUE TITLE
Why not show on first launch with control?

### ISSUE THREAD

**Issue by pj4533** [mdznr/What-s-New#15]
```
    // Nothing's new if this hasn't been registered before. (Shouldn't work on first launch).
    if ( ![self lastAppVersion] ) {
        return nil;
    }
```

I am asked to show our users what is new in this release of our app, so I integrate this control.  How do I explain that it doesn't show whats new in this release, only FUTURE releases?

I suppose I could put in some conditional logic for setting a fake previous version once? (by using the NSUserDefaults key MTZWhatsNewLastAppVersionKey)   That seems smelly tho...

Any suggestions?

**Comment by shanejs** [comment]
For my brand-new app, this is show I'm handling it - not sure if there's a better way.

NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    NSString *userid = [defaults objectForKey:@"userid"];
    
    if (userid == nil) {
        NSString *uuid = [[NSUUID UUID] UUIDString];
        NSLog(@"userid created: %@", uuid);
        
        [defaults setObject:uuid forKey:@"userid"];
        [defaults synchronize];
        // first time!
        [MTZWhatsNew performSelector:@selector(setLastAppVersion:) withObject:@"0.9"];
        
    }

**Comment by chetem** [comment]
I'm looking into using this project for a project of my own, but came across this issue today. I also want to show updates for the *first time* that I use What's New in my project so my pre-existing users can see updates. You mentioned there being a method `handleWhatsNew:sinceVersion:` but I don't see it anywhere. Has this change come about?

**Comment by chetem** [comment]
Correction: I've found the method. However, it doesn't seem to be contained in the pod. Will you be adding this to the pod by any chance?
