### ISSUE TITLE
Some UI bugs on iPad iOS 8.1

### ISSUE THREAD

**Issue by oleynikd** [mdznr/What-s-New#21]
Her's how What-s-New looks like on iPad iOS 8.1:

**Problems with header** (bottom margins and text quality):
![screen shot 2015-01-21 at 1 10 04 am](https://cloud.githubusercontent.com/assets/3976868/5828227/5be934c2-a10a-11e4-8543-09f8f48e6001.png)

**Problems with icon insets** (Stay up to date icon is lower then other):
![screen shot 2015-01-21 at 1 11 25 am](https://cloud.githubusercontent.com/assets/3976868/5828248/84a28a94-a10a-11e4-8759-d1c0a7fdb187.png)

Any ideas?

**Comment by mdznr** [comment]
This now requires iOS 9
