### ISSUE TITLE
Wrong LayoutItemSize?  A Proposed Solution.

### ISSUE THREAD

**Issue by sgorbyo** [mdznr/What-s-New#22]
Receiving a warning on layout running on iPad, I investigated and found what seems a problem between:

**MTZWhatsNewGridViewController.m**

```
- (void)calculateLayoutItemSize
{
    CGSize itemSize = [self shouldUseGridLayout] ? CGSizeMake(270, 187) : CGSizeMake(320, 108);
...
```

and

**MTZWhatsNewFeatureCollectionViewCell.m**

```
- (void)layoutForGrid
{
    ...
     // Vertical alignment.
     [self.contentView addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|-(>=0)-[icon(64)]-10-[title(20)]-4-[detail(34)]-(>=28)-|" options:NSLayoutFormatAlignAllCenterX metrics:nil views:views]];
}
```

With the following change everything seems to work:

```
- (void)calculateLayoutItemSize
{
    CGSize itemSize = [self shouldUseGridLayout] ? CGSizeMake(270, 187) : CGSizeMake(320, 160); // It was CGSizeMake(320, 108);
```

Please check it.

Thanks :-)

**Comment by mdznr** [comment]
![ios simulator screen shot may 5 2015 8 11 02 pm](https://cloud.githubusercontent.com/assets/963948/7486954/e82aa880-f362-11e4-9a36-96b9b6f3c9ae.png)
![ios simulator screen shot may 5 2015 8 11 10 pm](https://cloud.githubusercontent.com/assets/963948/7486955/e845fe6e-f362-11e4-8afa-64845c458225.png)
Changing it to 160 results in the screenshot on the right on iPhone.

**Comment by sgorbyo** [comment]
You are right, the problem was not there but in:

**MTZWhatsNewGridViewController.m**

    - (BOOL)shouldUseGridLayout
    {
	    // iPhone width = 320
	    // iPad's UIModalPresentationFormSheet width = 540
	    return self.collectionView.bounds.size.width >= 540;
    }

At the very beginning of Controllers instantiations it seems that self.collectionView being still not correctly dimensioned leads to wrong shouldUseGridLayout results and incoherence among layouts (itemSize for list layout is always used also for grid).

Changing shouldUseGridLayout to the following (and removing my previously suggested modifications) seems to work:

    - (BOOL)shouldUseGridLayout
    {
	    return ([UIDevice currentDevice].userInterfaceIdiom==UIUserInterfaceIdiomPad);
    }

Thanks for your attention and for sharing with us your good work.
