### ISSUE TITLE
Is there a mechanism for localizable strings?

### ISSUE THREAD

**Issue by thisisjeffwong** [mdznr/What-s-New#25]
If not, what do you think the easiest way to extend that would be?

thanks! We've been using your pod in our app for a while.

**Comment by mdznr** [comment]
Hey Jeff!

The best way to localize this would be to localize the .plist that contains your information. In Xcode’s Utilities’s File Inspector, you should be able to select different localizations. Doing this should create a copy of your file, in which you can then localize as needed.

![screen shot 2017-01-31 at 7 26 17 am](https://cloud.githubusercontent.com/assets/963948/22471263/bb419530-e786-11e6-97d7-cb059b5071ac.png)

**Comment by thisisjeffwong** [comment]
Thanks, that works great!
