### ISSUE TITLE
Button not working iOS 11

### ISSUE THREAD

**Issue by PauliusVindzigelskis** [mdznr/What-s-New#26]
iPad Air 2
iOS 11.2

Button is not working due to UIToolbar having another layer on top of UIButton. By replacing UIToolbar with UIView or UIButton by UIBarButton should fix a problem. Working on first solution and will create pull request when done

Pull Request: #27

**Comment by mdznr** [comment]
I haven't run this code in a while. Can you explain a bit more about the issue? Perhaps you could provide screenshots of the app running in Xcode’s [Visual Debugger](https://developer.apple.com/videos/play/wwdc2016/410/) of what is happening?

**Comment by PauliusVindzigelskis** [comment]
Sure

Bug:
<img width="1037" alt="problem_0" src="https://user-images.githubusercontent.com/2383901/34897470-bd9ef348-f7b3-11e7-8615-1fd0fa8a0a44.png">
<img width="312" alt="problem_1" src="https://user-images.githubusercontent.com/2383901/34897471-bdacbd20-f7b3-11e7-90ce-424238ecab5b.png">

PR Solution:
<img width="1034" alt="problemfix_0" src="https://user-images.githubusercontent.com/2383901/34897479-cc598146-f7b3-11e7-8e10-7be2757f4e15.png">
<img width="305" alt="problemfix_1" src="https://user-images.githubusercontent.com/2383901/34897480-cc663846-f7b3-11e7-997b-63a6a2d66f46.png">

**Comment by mdznr** [comment]
This should be fixed now
